//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DataLinkServer.rc
//
#define IDR_MAINFRAME                   128
#define IDB_ITEMS                       129
#define IDS_STATUS_SERVER               138
#define IDS_STATUS_WORK                 139
#define IDS_STATUS_STOP                 140
#define IDS_READY                       141
#define IDR_DATALINKSERVER              142
#define IDR_OPCDASERVER                 143
#define IDP_EXIT_CONFIRM                144
#define IDP_EXIT_ANYWAY_CONFIRM         145
#define IDS_REMOTE_GET_ARCH301          152
#define IDS_REMOTE_GET_PARAM            154
#define IDS_REMOTE_GET_CALENDAR         155
#define IDS_REMOTE_GET_TARIF            156
#define IDS_REMOTE_SET_CALENDAR         157
#define IDD_PP_PROP_EMPTY               159
#define IDD_PP_PROP_GENERAL             171
#define IDI_ICON_START                  175
#define IDI_ICON_STOP                   176
#define IDR_DATABASE_HISTORICAL         177
#define IDS_FILTERMDB                   178
#define IDR_POPUP_OUTPUT                179
#define IDR_POPUP_ITEM_TREE             206
#define IDS_FILTERALL                   225
#define IDR_POPUP_NOTIFY_ICON           231
#define IDR_POPUP_ITEM_LIST             232
#define ID_STATUSBAR_PANE_CURRENT_TIME  236
#define ID_STATUSBAR_PANE_OPC_OBJECTS   237
#define ID_STATUSBAR_PANE_TRANSACTIONS  238
#define IDS_FRMT_OPC_OBJECTS            239
#define IDS_FRMT_TRANSACTIONS           240
#define IDB_OUTPUT                      241
#define IDS_FRMT_STATUS                 242
#define ID_STATUSBAR_PANE_STATUS        245
#define IDS_REMOTE_SET_TARIF            246
#define IDS_REMOTE_DISABLE              251
#define IDS_REMOTE_SET_PARAM            252
#define IDS_MODULE_VERSION              256
#define IDS_STRING_FUN1                 257
#define ID_STATUSBAR_PANE_CHANNELS      258
#define IDS_FRMT_CHANNELS               259
#define IDD_ABOUTBOX                    287
#define IDD_PP_OPTIONS_GENERAL          288
#define IDD_PP_PROP_CHANNEL             289
#define IDD_PP_PROP_METER               290
#define IDD_PP_PROP_COLLECTOR           291
#define IDD_PP_PROP_POLL_GROUPS         292
#define IDD_PP_PROP_TAG                 293
#define IDD_POLL_GROUP                  294
#define IDD_PP_OPTIONS_INTERFACES       295
#define IDD_PP_OPTIONS_TIMEOUTS         300
#define IDD_PRE_POLL                    301
#define IDD_PP_PROP_DEVICE              302
#define IDD_PP_PROP_CHANNEL_SETTINGS    303
#define IDD_CHANNEL_SETTINGS            304
#define IDC_EDT_INDEX                   1020
#define IDC_EDT_TYPE                    1028
#define IDC_EDT_SERIAL_NUMBER           1029
#define IDC_CMB_PORT_BYTE_SIZE          1029
#define IDC_EDT_PORT                    1030
#define IDC_EDT_BEG_POLL_DATE           1031
#define IDC_EDT_END_POLL_DATE           1032
#define IDC_CMB_PORT_PARITY             1033
#define IDC_EDT_ID                      1033
#define IDC_CMB_PORT_NAME               1034
#define IDC_EDT_RESTYPE                 1034
#define IDC_CMB_PORT_STOP_BITS          1035
#define IDC_EDT_PROTOCOL_TYPE           1036
#define IDC_CMB_PORT_FLOW_CONTROL       1036
#define IDC_EDT_DESCRIPTION             1037
#define IDC_CMB_TYPE                    1037
#define IDC_EDT_PASSWORD1               1037
#define IDC_EDT_PASSWORD2               1038
#define IDC_CMB_RASCON                  1038
#define IDC_EDT_ADDRESS                 1039
#define IDC_EDT_CONFIG_MODE             1040
#define IDC_EDT_FULL_NAME               1041
#define IDC_EDT_NAME                    1045
#define IDC_EDT_MAX_FRAME_SIZE          1046
#define IDC_EDT_GUID                    1050
#define IDC_STC_FILE_VERSION            1051
#define IDC_EDT_FACTORY_NUMBER          1052
#define IDC_STC_COPYRIGHT               1053
#define IDC_EDT_VERSION                 1053
#define IDC_EDT_ISSUE_DATE              1054
#define IDC_CMB_PORT_BAUD_RATE          1057
#define IDC_STC_TITLE                   1060
#define IDC_CHK_AUTO_RUN                1074
#define IDC_CHK_ENABLE_CRC_RB           1075
#define IDC_CHK_ENABLE_CONFIG           1076
#define IDC_EDT_CONFIG_FILE             1078
#define IDC_BTN_BROWSE_CONFIG_FILE      1079
#define IDC_STATIC_SEPARATOR1           1081
#define IDC_STATIC_SEPARATOR2           1083
#define IDC_STATIC_SEPARATOR3           1084
#define IDC_STATIC_SEPARATOR4           1085
#define IDC_STATIC_SEPARATOR5           1086
#define IDC_STC_LABEL                   1100
#define IDC_CHK_DISABLED                1116
#define IDC_CHK_ARCHIVING_ENABLE        1118
#define IDC_EDT_CODE                    1119
#define IDC_EDT_CLASS                   1120
#define IDC_EDT_UNITS_TYPE              1121
#define IDC_EDT_UNITS_NAME              1122
#define IDC_EDT_ARCHIVING_TAG           1123
#define IDC_EDT_CHARACTER               1124
#define IDC_BTN_BROWSE_TAG              1125
#define IDC_EDT_ASSIGNMENT              1126
#define IDC_EDT_AUTO_CLOSE_TIMEOUT      1128
#define IDC_CHK_AUTO_CLOSE_ENABLED      1129
#define IDC_EDT_PORT_READ_INTERVAL_TIMEOUT 1130
#define IDC_EDT_PORT_READ_TIMEOUT_MULTIPLIER 1131
#define IDC_EDT_PORT_READ_TIMEOUT_CONSTANT 1132
#define IDC_EDT_PORT_WRITE_TIMEOUT_MULTIPLIER 1133
#define IDC_CHK_POLL_ENABLE             1133
#define IDC_EDT_PORT_WRITE_TIMEOUT_CONSTANT 1134
#define IDC_CMB_POLL_GROUP              1134
#define IDC_EDT_GROUPS                  1135
#define IDC_EDT_SEND_TIMEOUT            1135
#define IDC_EDT_RECV_TIMEOUT            1136
#define IDC_STC_COMMENT                 1137
#define IDC_CHK_DEBUG_CHANNELS          1138
#define IDC_CHK_DEBUG_TRANSACTIONS      1139
#define IDC_LST_GROUPS                  1140
#define IDC_CHK_DEBUG_REMOTING          1140
#define IDC_CHK_DEBUG_CRCRB             1141
#define IDC_CHK_DEBUG_DRIVERS           1142
#define IDC_BTN_ADD                     1143
#define IDC_CHK_DEBUG_CONFIG            1143
#define IDC_BTN_REMOVE                  1144
#define IDC_BTN_MODIFY                  1145
#define IDC_CMB_VIEW_TYPE               1146
#define IDC_CHK_DEBUG_POLL              1146
#define IDC_EDT_FREQ                    1155
#define IDC_EDT_AFTER_ERROR_FREQ        1156
#define IDC_EDT_POLL_ARCHIVE_AFTER_NODATA_FREQ 1157
#define IDC_CMB_FUNC                    1159
#define IDC_EDT_NET_REMOTING_URI        1159
#define IDC_EDT_NET_REMOTING_PORT       1160
#define IDC_EDT_CRC_RB_PORT             1161
#define IDC_CHK_ENABLE_NET_REMOTING     1162
#define IDC_BTN_DEFAULT                 1163
#define IDC_EDT_CRC_RB_HOST             1164
#define IDC_EDT_CONFIG_HOST             1165
#define IDC_EDT_CONFIG_PORT             1166
#define IDC_CHK_POLL_ARCHIVE            1171
#define IDC_EDT_MIN_RECONNECT_INTERVAL  1172
#define IDC_CHK_POLL_AFTER_ERROR        1172
#define IDC_CHK_POLL_ARCHIVE_AFTER_NODATA 1173
#define IDC_DTP_SCHEDULE_TIME           1176
#define IDC_CMB_SCHEDULE_TYPE           1177
#define IDC_EDT_DAYS                    1178
#define IDC_EDT_WEEKS                   1179
#define IDC_EDT_DAY_OF_MONTH            1180
#define IDC_STC_SCHEDULE_TIME           1181
#define IDC_EDT_POLL_ARCHIVE_DEEP       1182
#define IDC_EDT_POLL_TIMEOUT            1182
#define IDC_EDT_REMOTING_TIMEOUT        1183
#define IDC_EDT_CONFIG_TIMEOUT          1184
#define IDC_FUN_CLIST                   1188
#define IDC_CHECK_LAST_VALS             1191
#define IDC_CHECK_ARCH_VALS             1192
#define IDC_BTN_SEL_ALL                 1193
#define IDC_BTN_DESEL_ALL               1194
#define IDC_EDT_ADDRESS_IN_METER        1194
#define IDC_LST                         1195
#define IDC_CMB_CHANNEL                 1196
#define IDC_BTN_TEST                    1197
#define IDC_EDT_PHONE                   1198
#define IDC_EDT_ATTEMPT                 1199
#define IDC_EDT_HOST                    1200
#define IDC_EDT_RETRY_COUNT             1201
#define IDC_EDT_RETRY_TIMEOUT           1202
#define IDP_ERROR_FILE_IMPORT_METERS    5000
#define IDP_ERROR_FILE_IMPORT_DICT      5001
#define IDP_ERROR_FILE_EXPORT_HDA       5002
#define IDP_ERROR_FILE_EXPORT_TAGS      5003
#define IDP_ERROR_FILE_SAVE             5004
#define IDP_ERROR_FILE_CLOSE            5005
#define IDP_ERROR_FILE_OPEN             5006
#define IDP_ERROR_SAVE_OPTIONS          5007
#define IDP_ERROR_TESTCONN_CHAN         5008
#define IDP_ERROR_TESTCONN_CHAN_CREATE  5009
#define IDP_ERROR_TESTCONN_TRANS_EXEC   5010
#define IDP_ERROR_TESTCONN_TRANS_NOTCOMPLETE 5012
#define IDP_ERROR_TESTCONN_NOERR        5013
#define IDP_ERROR_TESTCONN_CHAN_DEFAULT 5014
#define IDP_DELETE_REQUEST              5017
#define IDP_DELETE_WARNING              5018
#define IDP_ERROR_COPY_TO_CLIP          5019
#define IDP_ERROR_PASTE_FROM_CLIP       5020
#define IDP_ERROR_RENAME                5021
#define IDS_TAG_TYPE_INVALID            6000
#define IDS_TAG_TYPE_CURRENT            6001
#define IDS_TAG_TYPE_ARCHIVAL           6002
#define IDS_TAG_TYPE_EVENT              6003
#define IDS_TAG_CLASS_INVALID           6004
#define IDS_TAG_CLASS_BASE              6005
#define IDS_TAG_CLASS_OPTIONAL          6006
#define IDS_TAG_CLASS_BASE2             6007
#define IDS_TAG_UNITS_TYPE_INVALID      6008
#define IDS_TAG_UNITS_TYPE_ANALOG       6009
#define IDS_TAG_UNITS_TYPE_DISCRETE     6010
#define IDS_TAG_ASSiGNMENT_INVALID      6011
#define IDS_TAG_CHAR_INVALID            6012
#define IDS_TAG_CHAR_30MIN              6013
#define IDS_TAG_CHAR_HOUR               6014
#define IDS_TAG_CHAR_DAY                6015
#define IDS_TAG_CHAR_MONTH              6016
#define IDS_TAG_CHAR_BEG_OF_MONTH       6017
#define IDS_TAG_CHAR_SUM                6018
#define IDS_TAG_CHAR_BEG_OF_DAY         6019
#define IDS_TAG_PROP_GUID               6020
#define IDS_TAG_PROP_ADDRESS            6021
#define IDS_TAG_PROP_CODE               6022
#define IDS_TAG_PROP_TYPE               6023
#define IDS_TAG_PROP_CLASS              6024
#define IDS_TAG_PROP_UNITS_TYPE         6025
#define IDS_TAG_PROP_UNITS_NAME         6026
#define IDS_TAG_PROP_CHAR               6027
#define IDS_TAG_PROP_ASSIGNMENT         6028
#define IDS_TAG_PROP_ADDRESS_IN_METER   6029
#define IDS_TAG_PROP_POLL_ENABLE        6030
#define IDS_TAG_PROP_POLL_GROUP         6031
#define IDS_TAG_PROP_ARCH_ENABLE        6032
#define IDS_TAG_PROP_ARCH_TAG           6033
#define IDS_CHAN_PROP_TYPE              6034
#define IDS_CHAN_PROP_PORT_NAME         6035
#define IDS_CHAN_PROP_PORT_BAUD_RATE    6036
#define IDS_CHAN_PROP_PORT_BYTE_SIZE    6037
#define IDS_CHAN_PROP_PORT_PARITY       6038
#define IDS_CHAN_PROP_PORT_STOP_BITS    6039
#define IDS_CHAN_PROP_PORT_FLOW_CONTROL 6040
#define IDS_CHAN_PROP_PORT_READ_INT_TIMEOUT 6041
#define IDS_CHAN_PROP_PORT_READ_TIMEOUT_MULT 6042
#define IDS_CHAN_PROP_PORT_READ_TIMEOUT_CONST 6043
#define IDS_CHAN_PROP_PORT_WRITE_TIMEOUT_MULT 6044
#define IDS_CHAN_PROP_PORT_WRITE_TIMEOUT_CONST 6045
#define IDS_CHAN_PROP_SEND              6046
#define IDS_CHAN_PROP_RECV              6047
#define IDS_CHAN_PROP_AUTOCLOSE_EN      6048
#define IDS_CHAN_PROP_AUTOCLOSE_TIMEOUT 6049
#define IDS_CHAN_PROP_RASCONN_NAME      6050
#define IDS_CHAN_TYPE_INVALID           6051
#define IDS_CHAN_TYPE_SERIAL            6052
#define IDS_CHAN_TYPE_DIALUP            6053
#define IDS_CHAN_TYPE_GSM               6054
#define IDS_CHAN_TYPE_ETH_UDP           6055
#define IDS_CHAN_TYPE_ETH_TCP           6056
#define IDS_CHAN_TYPE_RAS               6057
#define IDS_CHAN_PORT_PARITY_NONE       6058
#define IDS_CHAN_PORT_PARITY_ODD        6059
#define IDS_CHAN_PORT_PARITY_EVEN       6060
#define IDS_CHAN_PORT_PARITY_MARK       6061
#define IDS_CHAN_PORT_PARITY_SPACE      6062
#define IDS_CHAN_FLOWCTTRL_NONE         6063
#define IDS_CHAN_FLOWCTRL_HARDWARE      6064
#define IDS_CHAN_FLOWCTRL_MODEM         6065
#define IDS_DEV_PROP_GUID               6066
#define IDS_DEV_PROP_ADDR               6067
#define IDS_DEV_PROP_POLLGR             6068
#define IDS_DEV_PROP_CHANSET            6069
#define IDS_COLL_PROP_GUID              6070
#define IDS_COLL_PROP_ADDR              6071
#define IDS_COLL_PROP_CONF_MODE         6072
#define IDS_COLL_PROP_PASS_1            6073
#define IDS_COLL_PROP_PASS_2            6074
#define IDS_COLL_PROP_TYPE              6075
#define IDS_COLL_PROP_FACT_NUMBER       6076
#define IDS_COLL_PROP_VERS              6077
#define IDS_COLL_PROP_ISSDATE           6078
#define IDS_COLL_PROP_CHANSET           6079
#define IDS_COLL_PROP_POLLGR            6080
#define IDS_METER_PROP_GUID             6081
#define IDS_METER_PROP_ID               6082
#define IDS_METER_PROP_RES              6083
#define IDS_METER_PROP_TYPE_NUM         6084
#define IDS_METER_PROP_TYPE             6085
#define IDS_METER_PROP_SERIAL           6086
#define IDS_METER_PROP_ADDR             6087
#define IDS_METER_PROP_INDEX            6088
#define IDS_METER_PROP_PORT             6089
#define IDS_METER_PROP_DATE_POLL_START  6090
#define IDS_METER_PROP_DATE_POLL_END    6091
#define IDS_METER_PROP_PROT_TYPE        6092
#define IDS_METER_PROP_PASS_1           6093
#define IDS_METER_PROP_PASS_2           6094
#define IDS_METER_PROP_POLLGR           6095
#define IDS_METER_RESTYPE_UNKNOWN       6096
#define IDS_METER_RESTYPE_ELECTR        6097
#define IDS_METER_RESTYPE_HEAT          6098
#define IDS_METER_RESTYPE_WATER         6099
#define IDS_METER_RESTYPE_GAS           6100
#define IDS_DEFAULT_USPD_NAME           6102
#define IDS_EVTLOG_ITEM_NAME            6103
#define IDS_DEFAULT_METER_NAME          6104
#define IDS_DEFAULT_TAG_NAME            6105
#define IDS_CHAN_ITEM_NAME_PREF         6106
#define IDS_CHANGR_ITEM_NAME            6107
#define IDS_COLLGR_ITEM_NAME            6108
#define IDS_DEVGR_ITEM_NAME             6109
#define IDS_DEV_ITEM_NAME_PREF          6110
#define IDS_TAG_ITEM_NAME_PREF          6111
#define IDS_ITEM_BASENAME               6112
#define IDS_FUNC_NAME_01_DIRACCESS      6113
#define IDS_FUNC_NAME_02_UPDATETIME     6114
#define IDS_FUNC_NAME_03_ARCHVALUE      6115
#define IDS_FUNC_NAME_04_ARCHVALUES     6116
#define IDS_FUNC_NAME_05_CURVALUES      6117
#define IDS_FUNC_NAME_06_EVENTS         6118
#define IDS_FUNC_NAME_07_ARCHVALUES_MASK 6119
#define IDS_FUNC_NAME_14_ARCHVALUES     6120
#define IDS_FUNC_NAME_15_CURVALUES      6121
#define IDS_FUNC_NAME_16_EVENTS         6122
#define IDS_FUNC_NAME_P2_04_VALUES      6123
#define IDS_ERROR_NOERR                 6124
#define IDS_ERROR_NODATA                6125
#define IDS_ERROR_NULLDATA              6126
#define IDS_ERROR_UNKNOWN               6127
#define IDS_ERROR_TIMEOUT               6128
#define IDS_ERROR_SELECT_CHAN           6129
#define IDS_ERROR_OPEN_CHAN             6130
#define IDS_ERROR_SEND_DATA             6131
#define IDS_ERROR_RECV_DATA             6132
#define IDS_ERROR_WAIT_DATA             6133
#define IDS_ERROR_INVALID_REPLY_DATA    6134
#define IDS_ERROR_INVALID_REPLY_SIZE    6135
#define IDS_ERROR_INVALID_REPLY_FORMAT  6136
#define IDS_ERROR_BUILD_PACKET          6137
#define IDS_ERROR_PARSE_PACKET          6138
#define IDS_SHEDULE_TYPE_TASK_STARTUP   6139
#define IDS_SHEDULE_TYPE_TASK_DAILY     6140
#define IDS_SHEDULE_TYPE_TASK_MONTHLY   6142
#define IDS_SHEDULE_TYPE_TASK_WEEKLY    6143
#define IDS_SHEDULE_TYPE_TASK_STARTUP_FORMAT 6144
#define IDS_SHEDULE_TYPE_TASK_DAILY_FORMAT_ED 6145
#define IDS_SHEDULE_TYPE_TASK_WEEKLY_FORMAT_EW 6146
#define IDS_SHEDULE_TYPE_TASK_MONTHLY_FORMAT 6147
#define IDS_SHEDULE_TYPE_TASK_DAILY_FORMAT_NED 6148
#define IDS_SHEDULE_TYPE_TASK_WEEKLY_FORMAT_NEW 6149
#define IDS_WNDCOMBO_TABLE              6150
#define IDS_WNDCOMBO_TEXT               6151
#define IDS_NAMESPACE_COLUMNS_NUMBER    6152
#define IDS_NAMESPACE_COLUMNS_ID        6153
#define IDS_NAMESPACE_COLUMNS_NAME      6154
#define IDS_NAMESPACE_COLUMNS_DESCR     6155
#define IDS_NAMESPACE_COLUMNS_DISABLED  6156
#define IDS_NAMESPACE_COLUMNS_DISABLED_YES 6157
#define IDS_NAMESPACE_COLUMNS_DISABLED_NO 6158
#define IDS_NAMESPACE_COLUMNS_TYPE      6159
#define IDS_NAMESPACE_COLUMNS_SYMBOL    6160
#define IDS_NAMESPACE_COLUMNS_UNITS     6161
#define IDS_NAMESPACE_COLUMNS_VALUE     6163
#define IDS_NAMESPACE_COLUMNS_VALUE_DATA_TYPE 6164
#define IDS_NAMESPACE_COLUMNS_VALUE_QUALITY 6165
#define IDS_NAMESPACE_COLUMNS_VALUE_TIMESTAMP 6166
#define IDS_NAMESPACE_CONSTS_ROOT_NAME  6167
#define IDS_SERVER_STATUS_RUNNING       6168
#define IDS_SERVER_STATUS_FAILED        6169
#define IDS_SERVER_STATUS_NOCONFIG      6170
#define IDS_SERVER_STATUS_STOPPED       6171
#define IDS_SERVER_STATUS_TEST          6172
#define IDS_SERVER_STATUS_COMERR        6173
#define IDS_OUTPUT_COLUMNS_DATE         6174
#define IDS_OUTPUT_COLUMNS_TIME         6175
#define IDS_OUTPUT_COLUMNS_LEVEL        6176
#define IDS_OUTPUT_COLUMNS_ERROR        6177
#define IDS_OUTPUT_COLUMNS_MESSAGE      6178
#define IDS_CONST_PROP_TEXT_ERROR       6179
#define IDS_CONST_PROP_TEXT_UNAVAILABLE 6180
#define IDS_CONST_PROP_TEXT_NOTSPECIFIED 6181
#define IDS_CONST_PROP_TEXT_YES         6182
#define IDS_CONST_PROP_TEXT_NO          6183
#define IDS_CONST_WND_DEFAULT_TITLE     6184
#define IDS_CONST_WND_CONFIG_LIST_PANE  6185
#define IDS_CONST_WND_CONFIG_LIST_TREE  6186
#define IDS_CONST_WND_OUT_TREE          6187
#define IDS_CONST_WND_OPT_DIALOG        6188
#define IDS_CONST_WND_PROP_DIALOG       6189
#define IDS_FILTER_MDB                  6190
#define IDS_FILTER_XML                  6191
#define IDS_SAVE_FILE_FILTER            6192
#define IDS_FILTER_4SAVE                6192
#define IDS_FILTER_4LOAD                6194
#define IDS_FUNC_NAME_17_ARCHVALUES     6195
#define ID_FILE_IMPORT_METERS           32778
#define ID_FILE_IMPORT_DICTIONARY       32779
#define ID_VIEW_PROPERTIES              32780
#define ID_ACTION_RUN                   32783
#define ID_ACTION_STOP                  32784
#define ID_VIEW_OUTPUT                  32790
#define ID_TOOL_OPTIONS                 32805
#define ID_EDIT_CREATE_CHANNEL          32806
#define ID_VIEW_NAMESPACE_TREE          32809
#define ID_FILE_EXPORT_HDA              32810
#define ID_APP_SHOWHIDE                 32816
#define ID_EDIT_RENAME                  32819
#define ID_VIEW_GOTO_UP                 32830
#define ID_VIEW_TAGS_OPTIONAL           32831
#define ID_VIEW_ITEM_VALUES             32832
#define ID_FILE_EXPORT_TAGS             32833
#define ID_ACTION_POLL                  32834
#define ID_ACTION_CUSTOM_POLL           32836
#define ID_EDIT_CREATE_DEVICE           32838
#define ID_EDIT_CREATE_TAG              32839

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        306
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1203
#define _APS_NEXT_SYMED_VALUE           1217
#endif
#endif
